
networks:
  overlay_network:
    external: false
    name: overlay_network

services:
  # Database
  database:
    container_name: database
    image: mysql:8.0.37-bookworm
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - "3306:3306"  
    networks:
      - overlay_network
    environment:
        - MYSQL_ROOT_PASSWORD=mysql
        - MYSQL_DATABASE=db
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
    volumes:
        - ./data/mysql:/var/lib/mysql
        - ./init_database:/docker-entrypoint-initdb.d/:ro
  
  # Basic GUI for interacting with database
  adminer:
    container_name: db_admin
    image: adminer
    restart: always
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - overlay_network

  # UaaS backend
  uaas_backend:
    container_name: uaas_backend
    image: nchain/innovation-uaas-service:v1.2
    ports:
      - 9000:9000
    networks:
      - overlay_network
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    restart: on-failure

  # UaaS web API
  uaas_web:
    container_name: uaas_web
    image: nchain/innovation-uaas-web:v1.3
    ports:
      - 5010:5010
    networks:
      - overlay_network
    depends_on:
      - uaas_backend
    volumes:
    #  - ./python/src:/app/python
      - ./data:/app/data
    restart: on-failure
  
  financing_service:
    container_name: financing_service
    image: nchain/innovation-financing-service:v2.1
    ports:
      - 8082:8082
    networks:
      - overlay_network
    depends_on:
      - uaas_web
    volumes:
      - ./data:/app/bin/data
    restart: on-failure
  

  