@startuml
title Overlay Network - Application Dependencies


[tx_engine]


package Overlay-Network {
    [UaaS] 
    [FinancingService] 
    FS_API -down- [FinancingService] : provides
    UaaS_API -down- [UaaS] : provides


}

[ExampleApplication]

ExampleApplication -right-> "tx_engine": Uses (Python Library)
ExampleApplication .down.> UaaS_API: Calls
ExampleApplication .down.> FS_API: Calls
@enduml