@startuml
title Overlay Network - Appliction Dependencies


[tx_engine]


package Overlay-Network {
    [UaaS] 
    [FinancingService] 
}

[ExampleApplication]

ExampleApplication -right-> "tx_engine": Uses (Python Library)
ExampleApplication .down.> UaaS: Calls
ExampleApplication .down.> FinancingService: Calls
@enduml