
title Example App - Use Cases
left to right direction

actor User

package "Example App" {
    package Status {
        User --> (Get Status)
        note right
        Returns the status of 
        * Application
        * Financing Service (FS)
        * UaaS 
        end note
    }
    package "Application Admin" {
        User --> (Generate Application Key)
        note right
        Generates a blockchain keypair 
        that can be used in the App to sign transactions
        end note

        User --> (Delete Application Key)
        note right
        Removes the Application key
        end note
    }

    package "Financing Service Admin" {

        User --> (Generate Financing Service Info)
        note right
        Generates a blockchain keypair and identifier
        that can be used by the Financing service 
        to create funding transactions
        end note

        User --> (Delete Financing Service Info[id])

        User --> (Get Balance[id])
        note right
        Given the identifier
        returns the Balance from the FS
        end note
        User --> (Get Address[id])
        note right
        Given the identifier
        returns the associated Address the FS
        end note

    }
}

