@startuml
title Overlay Network - Key Sequence
hide footbox

actor User as U

participant ExampleApplication as EA


box "Overlay System"  #lightblue
    participant FinancingService as FS
    participant UTXO_as_a_Service as UaaS
end box

participant TestnetFaucet as TF
participant Blockchain as BC

group Setup_Financing_Service_Key

    U -> EA: create_financing_service_key(client_id)
    activate EA
    EA -> EA: generate_key()
    EA -> FS: add_financing_service_info\n(client_id, wif)
    activate FS
    FS --> EA: success
    deactivate FS
    EA --> U: success(Address)
    deactivate EA

end group

group Fund_Financing_Service_Key

    U -> TF : fund(Address)
    activate TF
    TF -> TF: fund(Address)
    TF --> U : success
    deactivate TF

end group

group Setup_Application_Key
    U -> EA: create_application_key()
    activate EA
    EA -> EA: generate_key()
    EA -> EA: set_application_key(wif)
    EA --> U: success
    deactivate EA
end group


group Create_Transaction
    U -> EA: create_tx()
    activate EA
    EA -> FS: create_funding_tx(client_id)
    activate FS
    FS -> FS: create_funding_tx(client_id)
    FS -> UaaS: broadcast(fund_tx)
    activate UaaS
    UaaS -> BC: broadcast(fund_tx)
    UaaS --> FS: success
    deactivate UaaS

    FS --> EA: fund_tx
    deactivate FS
    EA -> EA: create_tx(fund_tx)
    EA -> EA: sign_tx(tx, wif_key)

    EA -> UaaS: broadcast(tx)
    activate UaaS
    UaaS -> BC: broadcast(tx)
    UaaS --> EA: success
    deactivate UaaS


    EA --> U: success
    deactivate EA
end group


@enduml