@startuml
title Overlay Network - Overview

cloud "Blockchain" {
}

package "System" {

    [Example Application] 

    package "Overlay Network" {

        UaaS_API -down- [UaaS] : provides
        [UaaS] .down.> Blockchain: uses

        FS_API -down- [FinancingService] : provides
        [FinancingService] .up.> UaaS_API: uses
    }
}

[Example Application] ..> UaaS_API: uses
[Example Application] ..> FS_API: uses

@enduml